package com.xworkz.bt.runner;

import com.xworkz.bt.internal.*;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

public class ProductRunner {
    public static void main(String[] args) {
        System.out.println("ProductRunner is running...");

        Ward ward1 = new Ward(101, "Shantinagar", "Urban", "Mr. Ramesh Patil");
        Ward ward2 = new Ward(102, "Rajajinagar", "Urban", "Ms. Kavya Rao");
        Ward ward3 = new Ward(103, "Malleshwaram", "Urban", "Mr. Anil Kumar");
        Ward ward4 = new Ward(104, "BTM Layout", "Urban", "Ms. Priya Menon");
        Ward ward5 = new Ward(105, "Jayanagar", "Urban", "Mr. Suresh Naik");
        Ward ward6 = new Ward(106, "Koramangala", "Urban", "Mr. Ravi Desai");
        Ward ward7 = new Ward(107, "Indiranagar", "Urban", "Ms. Anuja Shetty");
        Ward ward8 = new Ward(108, "Marathahalli", "Urban", "Mr. Shankar Babu");
        Ward ward9 = new Ward(109, "Whitefield", "Urban", "Ms. Meena Rani");
        Ward ward10 = new Ward(110, "HSR Layout", "Urban", "Mr. Raghav Joshi");

        Ward ward11 = new Ward(111, "Hebbal", "Urban", "Mr. Ramesh Gowda");
        Ward ward12 = new Ward(112, "Yelahanka", "Urban", "Ms. Nandita R");
        Ward ward13 = new Ward(113, "Bannerghatta", "Semi-Urban", "Mr. Vijay Shekar");
        Ward ward14 = new Ward(114, "Electronic City", "Urban", "Mr. Harish Iyer");
        Ward ward15 = new Ward(115, "KR Puram", "Urban", "Ms. Geetha Patil");
        Ward ward16 = new Ward(116, "Majestic", "Urban", "Mr. Dayanand Reddy");
        Ward ward17 = new Ward(117, "Basavanagudi", "Urban", "Ms. Pooja Kulkarni");
        Ward ward18 = new Ward(118, "Banashankari", "Urban", "Mr. Vivek Nayak");
        Ward ward19 = new Ward(119, "RT Nagar", "Urban", "Ms. Sneha R");
        Ward ward20 = new Ward(120, "Kengeri", "Semi-Urban", "Mr. Kumaraswamy");

        Ward ward21 = new Ward(121, "Mysore Road", "Urban", "Ms. Divya D");
        Ward ward22 = new Ward(122, "Peenya", "Industrial", "Mr. Rohit M");
        Ward ward23 = new Ward(123, "Nagawara", "Urban", "Ms. Anjali Singh");
        Ward ward24 = new Ward(124, "Hulimavu", "Urban", "Mr. Arvind Raj");
        Ward ward25 = new Ward(125, "JP Nagar", "Urban", "Ms. Rekha Rao");
        Ward ward26 = new Ward(126, "Vijayanagar", "Urban", "Mr. Deepak Jain");
        Ward ward27 = new Ward(127, "Shivajinagar", "Urban", "Ms. Rukmini Joshi");
        Ward ward28 = new Ward(128, "Ulsoor", "Urban", "Mr. Tarun Mehta");
        Ward ward29 = new Ward(129, "Fraser Town", "Urban", "Ms. Fatima K");
        Ward ward30 = new Ward(130, "Domlur", "Urban", "Mr. Aravind Prakash");

        Ward ward31 = new Ward(131, "Magadi Road", "Semi-Urban", "Ms. Bhavana R");
        Ward ward32 = new Ward(132, "Bellandur", "Urban", "Mr. Kiran Dev");
        Ward ward33 = new Ward(133, "Sarjapur", "Urban", "Ms. Anu B");
        Ward ward34 = new Ward(134, "Kaggadasapura", "Urban", "Mr. Sachin K");
        Ward ward35 = new Ward(135, "HBR Layout", "Urban", "Ms. Sunitha Yadav");
        Ward ward36 = new Ward(136, "Sanjaynagar", "Urban", "Mr. Dinesh Pai");
        Ward ward37 = new Ward(137, "RMV 2nd Stage", "Urban", "Ms. Lavanya S");
        Ward ward38 = new Ward(138, "Nagarbhavi", "Urban", "Mr. Yogesh Naidu");
        Ward ward39 = new Ward(139, "Varthur", "Urban", "Ms. Rekha Jain");
        Ward ward40 = new Ward(140, "Attiguppe", "Urban", "Mr. Karthik Gowda");

        Ward ward41 = new Ward(141, "Chandra Layout", "Urban", "Ms. Nisha Patil");
        Ward ward42 = new Ward(142, "Vidyaranyapura", "Urban", "Mr. Ramesh Bhat");
        Ward ward43 = new Ward(143, "Girinagar", "Urban", "Ms. Padmini Rao");
        Ward ward44 = new Ward(144, "Kumaraswamy Layout", "Urban", "Mr. Ajay Menon");
        Ward ward45 = new Ward(145, "Kalyan Nagar", "Urban", "Ms. Aishwarya M");
        Ward ward46 = new Ward(146, "Thanisandra", "Urban", "Mr. Shreesha R");
        Ward ward47 = new Ward(147, "Bagalakunte", "Urban", "Ms. Rohini Shekar");
        Ward ward48 = new Ward(148, "Basaveshwaranagar", "Urban", "Mr. Naveen K");
        Ward ward49 = new Ward(149, "Laggere", "Urban", "Ms. Meenakshi D");
        Ward ward50 = new Ward(150, "Hoysalanagar", "Urban", "Mr. Pramod R");

        Ward ward51 = new Ward(151, "Sahakar Nagar", "Urban", "Ms. Sneha Dev");
        Ward ward52 = new Ward(152, "Jeevan Bima Nagar", "Urban", "Mr. Vinod Das");
        Ward ward53 = new Ward(153, "Kasturinagar", "Urban", "Ms. Neha Iyer");
        Ward ward54 = new Ward(154, "BTM 2nd Stage", "Urban", "Mr. Venkatesh Hegde");
        Ward ward55 = new Ward(155, "Kodichikkanahalli", "Urban", "Ms. Aarti N");
        Ward ward56 = new Ward(156, "Chickpet", "Urban", "Mr. Sanjay K");
        Ward ward57 = new Ward(157, "Gandhi Bazaar", "Urban", "Ms. Latha R");
        Ward ward58 = new Ward(158, "Srirampura", "Urban", "Mr. Rakesh Bhat");
        Ward ward59 = new Ward(159, "Padmanabhanagar", "Urban", "Ms. Kavitha D");
        Ward ward60 = new Ward(160, "Subramanyanagar", "Urban", "Mr. Manoj Krishna");

        Ward ward61 = new Ward(161, "Sunkadakatte", "Semi-Urban", "Ms. Bhuvana S");
        Ward ward62 = new Ward(162, "Dasarahalli", "Urban", "Mr. Pradeep R");
        Ward ward63 = new Ward(163, "Yeshwanthpur", "Urban", "Ms. Savitha G");
        Ward ward64 = new Ward(164, "Vijaya Bank Layout", "Urban", "Mr. Sudhir Kumar");
        Ward ward65 = new Ward(165, "Devanahalli", "Rural", "Ms. Shweta Rao");


        Constituency c1 = new Constituency(201, "Bangalore South", "Urban", "Mr. Rajeev Shetty", ward1);
        Constituency c2 = new Constituency(202, "Bangalore North", "Urban", "Ms. Anuradha M", ward2);
        Constituency c3 = new Constituency(203, "Bangalore Central", "Urban", "Mr. Suraj Kulkarni", ward3);
        Constituency c4 = new Constituency(204, "BTM Zone", "Urban", "Ms. Rekha Hegde", ward4);
        Constituency c5 = new Constituency(205, "Jayanagar Zone", "Urban", "Mr. Nandan Pai", ward5);
        Constituency c6 = new Constituency(206, "Koramangala Zone", "Urban", "Ms. Tara Reddy", ward6);
        Constituency c7 = new Constituency(207, "Indiranagar Zone", "Urban", "Mr. Ashok Kumar", ward7);
        Constituency c8 = new Constituency(208, "Marathahalli Sector", "Urban", "Ms. Veena Rao", ward8);
        Constituency c9 = new Constituency(209, "Whitefield Zone", "Urban", "Mr. Ganesh Nayak", ward9);
        Constituency c10 = new Constituency(210, "HSR Sector", "Urban", "Ms. Deepika Iyer", ward10);

        Constituency c11 = new Constituency(211, "Hebbal Zone", "Urban", "Mr. Vikas Shetty", ward11);
        Constituency c12 = new Constituency(212, "Yelahanka Zone", "Urban", "Ms. Shruthi Rao", ward12);
        Constituency c13 = new Constituency(213, "Bannerghatta Region", "Semi-Urban", "Mr. Abhinav Dev", ward13);
        Constituency c14 = new Constituency(214, "Electronic Zone", "Urban", "Ms. Priya Shekar", ward14);
        Constituency c15 = new Constituency(215, "KR Puram Zone", "Urban", "Mr. Balaji N", ward15);
        Constituency c16 = new Constituency(216, "Majestic Sector", "Urban", "Ms. Leela Patil", ward16);
        Constituency c17 = new Constituency(217, "Basavanagudi Area", "Urban", "Mr. Rithvik Joshi", ward17);
        Constituency c18 = new Constituency(218, "Banashankari Zone", "Urban", "Ms. Laxmi Naidu", ward18);
        Constituency c19 = new Constituency(219, "RT Nagar Zone", "Urban", "Mr. Karthik Hegde", ward19);
        Constituency c20 = new Constituency(220, "Kengeri Zone", "Semi-Urban", "Ms. Aarthi N", ward20);

        Constituency c21 = new Constituency(221, "Mysore Road Sector", "Urban", "Mr. Shyam Dev", ward21);
        Constituency c22 = new Constituency(222, "Peenya Zone", "Industrial", "Ms. Bhavya Rao", ward22);
        Constituency c23 = new Constituency(223, "Nagawara Sector", "Urban", "Mr. Aditya R", ward23);
        Constituency c24 = new Constituency(224, "Hulimavu Area", "Urban", "Ms. Sneha Gowda", ward24);
        Constituency c25 = new Constituency(225, "JP Nagar Sector", "Urban", "Mr. Tejas Shetty", ward25);
        Constituency c26 = new Constituency(226, "Vijayanagar Sector", "Urban", "Ms. Reshma N", ward26);
        Constituency c27 = new Constituency(227, "Shivajinagar Zone", "Urban", "Mr. Bharat D", ward27);
        Constituency c28 = new Constituency(228, "Ulsoor Area", "Urban", "Ms. Ananya V", ward28);
        Constituency c29 = new Constituency(229, "Fraser Town Zone", "Urban", "Mr. Mukesh M", ward29);
        Constituency c30 = new Constituency(230, "Domlur Sector", "Urban", "Ms. Kavitha R", ward30);

        Constituency c31 = new Constituency(231, "Magadi Sector", "Semi-Urban", "Mr. Gaurav M", ward31);
        Constituency c32 = new Constituency(232, "Bellandur Zone", "Urban", "Ms. Meera Shetty", ward32);
        Constituency c33 = new Constituency(233, "Sarjapur Zone", "Urban", "Mr. Vinay S", ward33);
        Constituency c34 = new Constituency(234, "Kaggadasapura Sector", "Urban", "Ms. Janani Iyer", ward34);
        Constituency c35 = new Constituency(235, "HBR Layout Zone", "Urban", "Mr. Parth R", ward35);
        Constituency c36 = new Constituency(236, "Sanjaynagar Sector", "Urban", "Ms. Divya N", ward36);
        Constituency c37 = new Constituency(237, "RMV Zone", "Urban", "Mr. Sandeep B", ward37);
        Constituency c38 = new Constituency(238, "Nagarbhavi Area", "Urban", "Ms. Rachana K", ward38);
        Constituency c39 = new Constituency(239, "Varthur Zone", "Urban", "Mr. Prateek M", ward39);
        Constituency c40 = new Constituency(240, "Attiguppe Sector", "Urban", "Ms. Varsha D", ward40);

        Constituency c41 = new Constituency(241, "Chandra Layout", "Urban", "Mr. Lokesh Rao", ward41);
        Constituency c42 = new Constituency(242, "Vidyaranyapura", "Urban", "Ms. Sandhya N", ward42);
        Constituency c43 = new Constituency(243, "Girinagar Sector", "Urban", "Mr. Arun Joshi", ward43);
        Constituency c44 = new Constituency(244, "Kumaraswamy Layout", "Urban", "Ms. Megha S", ward44);
        Constituency c45 = new Constituency(245, "Kalyan Nagar", "Urban", "Mr. Arvind Das", ward45);
        Constituency c46 = new Constituency(246, "Thanisandra Area", "Urban", "Ms. Purnima R", ward46);
        Constituency c47 = new Constituency(247, "Bagalakunte", "Urban", "Mr. Nishanth Pai", ward47);
        Constituency c48 = new Constituency(248, "Basaveshwaranagar", "Urban", "Ms. Sneha J", ward48);
        Constituency c49 = new Constituency(249, "Laggere Sector", "Urban", "Mr. Ajith Kumar", ward49);
        Constituency c50 = new Constituency(250, "Hoysalanagar", "Urban", "Ms. Shraddha B", ward50);

        Constituency c51 = new Constituency(251, "Sahakar Nagar", "Urban", "Mr. Rajan Iyer", ward51);
        Constituency c52 = new Constituency(252, "Jeevan Bima Nagar", "Urban", "Ms. Pranita Shetty", ward52);
        Constituency c53 = new Constituency(253, "Kasturinagar", "Urban", "Mr. Ramesh H", ward53);
        Constituency c54 = new Constituency(254, "BTM 2nd Stage", "Urban", "Ms. Ritu M", ward54);
        Constituency c55 = new Constituency(255, "Kodichikkanahalli", "Urban", "Mr. Sachin K", ward55);
        Constituency c56 = new Constituency(256, "Chickpet", "Urban", "Ms. Sonal R", ward56);
        Constituency c57 = new Constituency(257, "Gandhi Bazaar", "Urban", "Mr. Anoop Nayak", ward57);
        Constituency c58 = new Constituency(258, "Srirampura", "Urban", "Ms. Nalini Rao", ward58);
        Constituency c59 = new Constituency(259, "Padmanabhanagar", "Urban", "Mr. Omkar Desai", ward59);
        Constituency c60 = new Constituency(260, "Subramanyanagar", "Urban", "Ms. Pooja H", ward60);

        Constituency c61 = new Constituency(261, "Sunkadakatte", "Semi-Urban", "Mr. Naveen Dev", ward61);
        Constituency c62 = new Constituency(262, "Dasarahalli", "Urban", "Ms. Anitha Rao", ward62);
        Constituency c63 = new Constituency(263, "Yeshwanthpur", "Urban", "Mr. Gautam R", ward63);
        Constituency c64 = new Constituency(264, "Vijaya Bank Layout", "Urban", "Ms. Preeti M", ward64);
        Constituency c65 = new Constituency(265, "Devanahalli", "Rural", "Mr. Vikas Patil", ward65);

        PrimeMinister pm1 = new PrimeMinister("PM_Name_1", "Party_B", "46", "Education_2", c1);
        PrimeMinister pm2 = new PrimeMinister("PM_Name_2", "Party_C", "47", "Education_3", c2);
        PrimeMinister pm3 = new PrimeMinister("PM_Name_3", "Party_D", "48", "Education_4", c3);
        PrimeMinister pm4 = new PrimeMinister("PM_Name_4", "Party_E", "49", "Education_5", c4);
        PrimeMinister pm5 = new PrimeMinister("PM_Name_5", "Party_F", "50", "Education_1", c5);
        PrimeMinister pm6 = new PrimeMinister("PM_Name_6", "Party_G", "51", "Education_2", c6);
        PrimeMinister pm7 = new PrimeMinister("PM_Name_7", "Party_H", "52", "Education_3", c7);
        PrimeMinister pm8 = new PrimeMinister("PM_Name_8", "Party_I", "53", "Education_4", c8);
        PrimeMinister pm9 = new PrimeMinister("PM_Name_9", "Party_J", "54", "Education_5", c9);
        PrimeMinister pm10 = new PrimeMinister("PM_Name_10", "Party_K", "45", "Education_1", c10);
        PrimeMinister pm11 = new PrimeMinister("PM_Name_11", "Party_L", "46", "Education_2", c11);
        PrimeMinister pm12 = new PrimeMinister("PM_Name_12", "Party_M", "47", "Education_3", c12);
        PrimeMinister pm13 = new PrimeMinister("PM_Name_13", "Party_N", "48", "Education_4", c13);
        PrimeMinister pm14 = new PrimeMinister("PM_Name_14", "Party_O", "49", "Education_5", c14);
        PrimeMinister pm15 = new PrimeMinister("PM_Name_15", "Party_P", "50", "Education_1", c15);
        PrimeMinister pm16 = new PrimeMinister("PM_Name_16", "Party_Q", "51", "Education_2", c16);
        PrimeMinister pm17 = new PrimeMinister("PM_Name_17", "Party_R", "52", "Education_3", c17);
        PrimeMinister pm18 = new PrimeMinister("PM_Name_18", "Party_S", "53", "Education_4", c18);
        PrimeMinister pm19 = new PrimeMinister("PM_Name_19", "Party_T", "54", "Education_5", c19);
        PrimeMinister pm20 = new PrimeMinister("PM_Name_20", "Party_U", "45", "Education_1", c20);
        PrimeMinister pm21 = new PrimeMinister("PM_Name_21", "Party_V", "46", "Education_2", c21);
        PrimeMinister pm22 = new PrimeMinister("PM_Name_22", "Party_W", "47", "Education_3", c22);
        PrimeMinister pm23 = new PrimeMinister("PM_Name_23", "Party_X", "48", "Education_4", c23);
        PrimeMinister pm24 = new PrimeMinister("PM_Name_24", "Party_Y", "49", "Education_5", c24);
        PrimeMinister pm25 = new PrimeMinister("PM_Name_25", "Party_Z", "50", "Education_1", c25);
        PrimeMinister pm26 = new PrimeMinister("PM_Name_26", "Party_A", "51", "Education_2", c26);
        PrimeMinister pm27 = new PrimeMinister("PM_Name_27", "Party_B", "52", "Education_3", c27);
        PrimeMinister pm28 = new PrimeMinister("PM_Name_28", "Party_C", "53", "Education_4", c28);
        PrimeMinister pm29 = new PrimeMinister("PM_Name_29", "Party_D", "54", "Education_5", c29);
        PrimeMinister pm30 = new PrimeMinister("PM_Name_30", "Party_E", "45", "Education_1", c30);
        PrimeMinister pm31 = new PrimeMinister("PM_Name_31", "Party_F", "46", "Education_2", c31);
        PrimeMinister pm32 = new PrimeMinister("PM_Name_32", "Party_G", "47", "Education_3", c32);
        PrimeMinister pm33 = new PrimeMinister("PM_Name_33", "Party_H", "48", "Education_4", c33);
        PrimeMinister pm34 = new PrimeMinister("PM_Name_34", "Party_I", "49", "Education_5", c34);
        PrimeMinister pm35 = new PrimeMinister("PM_Name_35", "Party_J", "50", "Education_1", c35);
        PrimeMinister pm36 = new PrimeMinister("PM_Name_36", "Party_K", "51", "Education_2", c36);
        PrimeMinister pm37 = new PrimeMinister("PM_Name_37", "Party_L", "52", "Education_3", c37);
        PrimeMinister pm38 = new PrimeMinister("PM_Name_38", "Party_M", "53", "Education_4", c38);
        PrimeMinister pm39 = new PrimeMinister("PM_Name_39", "Party_N", "54", "Education_5", c39);
        PrimeMinister pm40 = new PrimeMinister("PM_Name_40", "Party_O", "45", "Education_1", c40);
        PrimeMinister pm41 = new PrimeMinister("PM_Name_41", "Party_P", "46", "Education_2", c41);
        PrimeMinister pm42 = new PrimeMinister("PM_Name_42", "Party_Q", "47", "Education_3", c42);
        PrimeMinister pm43 = new PrimeMinister("PM_Name_43", "Party_R", "48", "Education_4", c43);
        PrimeMinister pm44 = new PrimeMinister("PM_Name_44", "Party_S", "49", "Education_5", c44);
        PrimeMinister pm45 = new PrimeMinister("PM_Name_45", "Party_T", "50", "Education_1", c45);
        PrimeMinister pm46 = new PrimeMinister("PM_Name_46", "Party_U", "51", "Education_2", c46);
        PrimeMinister pm47 = new PrimeMinister("PM_Name_47", "Party_V", "52", "Education_3", c47);
        PrimeMinister pm48 = new PrimeMinister("PM_Name_48", "Party_W", "53", "Education_4", c48);
        PrimeMinister pm49 = new PrimeMinister("PM_Name_49", "Party_X", "54", "Education_5", c49);
        PrimeMinister pm50 = new PrimeMinister("PM_Name_50", "Party_Y", "45", "Education_1", c50);
        PrimeMinister pm51 = new PrimeMinister("PM_Name_51", "Party_Z", "46", "Education_2", c51);
        PrimeMinister pm52 = new PrimeMinister("PM_Name_52", "Party_A", "47", "Education_3", c52);
        PrimeMinister pm53 = new PrimeMinister("PM_Name_53", "Party_B", "48", "Education_4", c53);
        PrimeMinister pm54 = new PrimeMinister("PM_Name_54", "Party_C", "49", "Education_5", c54);
        PrimeMinister pm55 = new PrimeMinister("PM_Name_55", "Party_D", "50", "Education_1", c55);
        PrimeMinister pm56 = new PrimeMinister("PM_Name_56", "Party_E", "51", "Education_2", c56);
        PrimeMinister pm57 = new PrimeMinister("PM_Name_57", "Party_F", "52", "Education_3", c57);
        PrimeMinister pm58 = new PrimeMinister("PM_Name_58", "Party_G", "53", "Education_4", c58);
        PrimeMinister pm59 = new PrimeMinister("PM_Name_59", "Party_H", "54", "Education_5", c59);
        PrimeMinister pm60 = new PrimeMinister("PM_Name_60", "Party_I", "45", "Education_1", c60);
        PrimeMinister pm61 = new PrimeMinister("PM_Name_61", "Party_J", "46", "Education_2", c61);
        PrimeMinister pm62 = new PrimeMinister("PM_Name_62", "Party_K", "47", "Education_3", c62);
        PrimeMinister pm63 = new PrimeMinister("PM_Name_63", "Party_L", "48", "Education_4", c63);
        PrimeMinister pm64 = new PrimeMinister("PM_Name_64", "Party_M", "49", "Education_5", c64);
        PrimeMinister pm65 = new PrimeMinister("PM_Name_65", "Party_N", "50", "Education_1", c65);

        Government govt1 = new Government("Democracy", "President", "01-01-2020", "31-12-2024", pm1);
        Government govt2 = new Government("Democracy", "President", "01-01-2021", "31-12-2025", pm2);
        Government govt3 = new Government("Democracy", "President", "01-01-2022", "31-12-2026", pm3);
        Government govt4 = new Government("Democracy", "President", "01-01-2023", "31-12-2027", pm4);
        Government govt5 = new Government("Democracy", "President", "01-01-2024", "31-12-2028", pm5);
        Government govt6 = new Government("Democracy", "President", "01-01-2025", "31-12-2029", pm6);
        Government govt7 = new Government("Democracy", "President", "01-01-2026", "31-12-2030", pm7);
        Government govt8 = new Government("Democracy", "President", "01-01-2027", "31-12-2031", pm8);
        Government govt9 = new Government("Democracy", "President", "01-01-2028", "31-12-2032", pm9);
        Government govt10 = new Government("Democracy", "President", "01-01-2029", "31-12-2033", pm10);
        Government govt11 = new Government("Democracy", "President", "01-01-2030", "31-12-2034", pm11);
        Government govt12 = new Government("Democracy", "President", "01-01-2031", "31-12-2035", pm12);
        Government govt13 = new Government("Democracy", "President", "01-01-2032", "31-12-2036", pm13);
        Government govt14 = new Government("Democracy", "President", "01-01-2033", "31-12-2037", pm14);
        Government govt15 = new Government("Democracy", "President", "01-01-2034", "31-12-2038", pm15);
        Government govt16 = new Government("Democracy", "President", "01-01-2035", "31-12-2039", pm16);
        Government govt17 = new Government("Democracy", "President", "01-01-2036", "31-12-2040", pm17);
        Government govt18 = new Government("Democracy", "President", "01-01-2037", "31-12-2041", pm18);
        Government govt19 = new Government("Democracy", "President", "01-01-2038", "31-12-2042", pm19);
        Government govt20 = new Government("Democracy", "President", "01-01-2039", "31-12-2043", pm20);
        Government govt21 = new Government("Democracy", "President", "01-01-2040", "31-12-2044", pm21);
        Government govt22 = new Government("Democracy", "President", "01-01-2041", "31-12-2045", pm22);
        Government govt23 = new Government("Democracy", "President", "01-01-2042", "31-12-2046", pm23);
        Government govt24 = new Government("Democracy", "President", "01-01-2043", "31-12-2047", pm24);
        Government govt25 = new Government("Democracy", "President", "01-01-2044", "31-12-2048", pm25);
        Government govt26 = new Government("Democracy", "President", "01-01-2045", "31-12-2049", pm26);
        Government govt27 = new Government("Democracy", "President", "01-01-2046", "31-12-2050", pm27);
        Government govt28 = new Government("Democracy", "President", "01-01-2047", "31-12-2051", pm28);
        Government govt29 = new Government("Democracy", "President", "01-01-2048", "31-12-2052", pm29);
        Government govt30 = new Government("Democracy", "President", "01-01-2049", "31-12-2053", pm30);
        Government govt31 = new Government("Democracy", "President", "01-01-2050", "31-12-2054", pm31);
        Government govt32 = new Government("Democracy", "President", "01-01-2051", "31-12-2055", pm32);
        Government govt33 = new Government("Democracy", "President", "01-01-2052", "31-12-2056", pm33);
        Government govt34 = new Government("Democracy", "President", "01-01-2053", "31-12-2057", pm34);
        Government govt35 = new Government("Democracy", "President", "01-01-2054", "31-12-2058", pm35);
        Government govt36 = new Government("Democracy", "President", "01-01-2055", "31-12-2059", pm36);
        Government govt37 = new Government("Democracy", "President", "01-01-2056", "31-12-2060", pm37);
        Government govt38 = new Government("Democracy", "President", "01-01-2057", "31-12-2061", pm38);
        Government govt39 = new Government("Democracy", "President", "01-01-2058", "31-12-2062", pm39);
        Government govt40 = new Government("Democracy", "President", "01-01-2059", "31-12-2063", pm40);
        Government govt41 = new Government("Democracy", "President", "01-01-2060", "31-12-2064", pm41);
        Government govt42 = new Government("Democracy", "President", "01-01-2061", "31-12-2065", pm42);
        Government govt43 = new Government("Democracy", "President", "01-01-2062", "31-12-2066", pm43);
        Government govt44 = new Government("Democracy", "President", "01-01-2063", "31-12-2067", pm44);
        Government govt45 = new Government("Democracy", "President", "01-01-2064", "31-12-2068", pm45);
        Government govt46 = new Government("Democracy", "President", "01-01-2065", "31-12-2069", pm46);
        Government govt47 = new Government("Democracy", "President", "01-01-2066", "31-12-2070", pm47);
        Government govt48 = new Government("Democracy", "President", "01-01-2067", "31-12-2071", pm48);
        Government govt49 = new Government("Democracy", "President", "01-01-2068", "31-12-2072", pm49);
        Government govt50 = new Government("Democracy", "President", "01-01-2069", "31-12-2073", pm50);
        Government govt51 = new Government("Democracy", "President", "01-01-2070", "31-12-2074", pm51);
        Government govt52 = new Government("Democracy", "President", "01-01-2071", "31-12-2075", pm52);
        Government govt53 = new Government("Democracy", "President", "01-01-2072", "31-12-2076", pm53);
        Government govt54 = new Government("Democracy", "President", "01-01-2073", "31-12-2077", pm54);
        Government govt55 = new Government("Democracy", "President", "01-01-2074", "31-12-2078", pm55);
        Government govt56 = new Government("Democracy", "President", "01-01-2075", "31-12-2079", pm56);
        Government govt57 = new Government("Democracy", "President", "01-01-2076", "31-12-2080", pm57);
        Government govt58 = new Government("Democracy", "President", "01-01-2077", "31-12-2081", pm58);
        Government govt59 = new Government("Democracy", "President", "01-01-2078", "31-12-2082", pm59);
        Government govt60 = new Government("Democracy", "President", "01-01-2079", "31-12-2083", pm60);
        Government govt61 = new Government("Democracy", "President", "01-01-2080", "31-12-2084", pm61);
        Government govt62 = new Government("Democracy", "President", "01-01-2081", "31-12-2085", pm62);
        Government govt63 = new Government("Democracy", "President", "01-01-2082", "31-12-2086", pm63);
        Government govt64 = new Government("Democracy", "President", "01-01-2083", "31-12-2087", pm64);
        Government govt65 = new Government("Democracy", "President", "01-01-2084", "31-12-2088", pm65);

        Tax tax1 = new Tax("Corporate Tax", 22.0, "Direct", "Corporate Tax Authority",govt1);
        Tax tax2 = new Tax("Income Tax", 30.0, "Direct", "Income Tax Department",govt2);
        Tax tax3 = new Tax("Goods and Services Tax", 18.0, "Indirect", "GST Council",govt3);
        Tax tax4 = new Tax("Value Added Tax", 14.5, "Indirect", "State VAT Department",govt4);
        Tax tax5 = new Tax("Property Tax", 1.0, "Direct", "Municipal Corporation",govt5);
        Tax tax6 = new Tax("Excise Duty", 12.0, "Indirect", "Central Excise Department",govt6);
        Tax tax7 = new Tax("Customs Duty", 10.0, "Indirect", "Customs Department",govt7);
        Tax tax8 = new Tax("Capital Gains Tax", 20.0, "Direct", "Income Tax Department",govt8);
        Tax tax9 = new Tax("Wealth Tax", 1.0, "Direct", "Wealth Tax Department",govt9);
        Tax tax10 = new Tax("Service Tax", 15.0, "Indirect", "Service Tax Department",govt10);
        Tax tax11 = new Tax("Cess on Income", 4.0, "Direct", "Income Tax Department",govt11);
        Tax tax12 = new Tax("Cess on Goods", 2.0, "Indirect", "GST Council",govt12);
        Tax tax13 = new Tax("Education Cess", 3.0, "Direct", "Income Tax Department",govt13);
        Tax tax14 = new Tax("Health Cess", 2.0, "Direct", "Income Tax Department",govt14);
        Tax tax15 = new Tax("Luxury Tax", 10.0, "Indirect", "State Luxury Tax Department",govt15);
        Tax tax16 = new Tax("Entertainment Tax", 20.0, "Indirect", "State Entertainment Tax Department",govt16);
        Tax tax17 = new Tax("Stamp Duty", 5.0, "Direct", "State Stamp Duty Department",govt17);
        Tax tax18 = new Tax("Registration Fees", 1.0, "Direct", "State Registration Department",govt18);
        Tax tax19 = new Tax("Professional Tax", 2.0, "Direct", "State Professional Tax Department",govt19);
        Tax tax20 = new Tax("Road Tax", 3.0, "Direct", "State Transport Department",govt20);
        Tax tax21 = new Tax("Sales Tax", 5.0, "Indirect", "State Sales Tax Department",govt21);
        Tax tax22 = new Tax("Excise on Alcohol", 25.0, "Indirect", "State Excise Department",govt22);
        Tax tax23 = new Tax("Excise on Tobacco", 50.0, "Indirect", "State Excise Department",govt23);
        Tax tax24 = new Tax("Environmental Cess", 1.0, "Direct", "Environmental Protection Agency",govt24);
        Tax tax25 = new Tax("Carbon Tax", 5.0, "Direct", "Environmental Protection Agency",govt25);
        Tax tax26 = new Tax("Digital Services Tax", 2.0, "Indirect", "Digital Services Department",govt26);
        Tax tax27 = new Tax("Luxury Vehicle Tax", 10.0, "Direct", "State Transport Department",govt27);
        Tax tax28 = new Tax("Green Tax", 1.0, "Direct", "Environmental Protection Agency",govt28);
        Tax tax29 = new Tax("Agricultural Income Tax", 0.0, "Direct", "Agricultural Department",govt29);
        Tax tax30 = new Tax("Import Duty", 15.0, "Indirect", "Customs Department",govt30);
        Tax tax31 = new Tax("Export Duty", 5.0, "Indirect", "Customs Department",govt31);
        Tax tax32 = new Tax("Digital Goods Tax", 3.0, "Indirect", "Digital Services Department",govt32);
        Tax tax33 = new Tax("Financial Transaction Tax", 0.1, "Direct", "Financial Regulatory Authority",govt33);
        Tax tax34 = new Tax("Insurance Premium Tax", 18.0, "Indirect", "Insurance Regulatory Authority",govt34);
        Tax tax35 = new Tax("Luxury Goods Tax", 20.0, "Indirect", "Luxury Goods Department",govt35);
        Tax tax36 = new Tax("Wealth Cess", 1.0, "Direct", "Wealth Tax Department",govt36);
        Tax tax37 = new Tax("Digital Content Tax", 5.0, "Indirect", "Digital Services Department",govt37);
        Tax tax38 = new Tax("Gaming Tax", 10.0, "Indirect", "Gaming Regulatory Authority",govt38);
        Tax tax39 = new Tax("Cryptocurrency Tax", 30.0, "Direct", "Cryptocurrency Regulatory Authority",govt39);
        Tax tax40 = new Tax("E-commerce Tax", 5.0, "Indirect", "E-commerce Regulatory Authority",govt40);
        Tax tax41 = new Tax("Luxury Property Tax", 2.0, "Direct", "Property Tax Department",govt41);
        Tax tax42 = new Tax("Digital Advertising Tax", 5.0, "Indirect", "Digital Advertising Authority",govt42);
        Tax tax43 = new Tax("Carbon Emission Tax", 10.0, "Direct", "Environmental Protection Agency",govt43);
        Tax tax44 = new Tax("Plastic Waste Tax", 1.0, "Direct", "Environmental Protection Agency",govt44);
        Tax tax45 = new Tax("Water Usage Tax", 0.5, "Direct", "Water Resources Department",govt45);
        Tax tax46 = new Tax("Waste Management Tax", 2.0, "Direct", "Waste Management Department",govt46);
        Tax tax47 = new Tax("Renewable Energy Tax", 1.0, "Direct", "Renewable Energy Department",govt47);
        Tax tax48 = new Tax("Digital Payment Tax", 0.5, "Indirect", "Digital Payment Authority",govt48);
        Tax tax49 = new Tax("Luxury Travel Tax", 10.0, "Indirect", "Travel Regulatory Authority",govt49);
        Tax tax50 = new Tax("Luxury Hotel Tax", 15.0, "Indirect", "Hotel Regulatory Authority",govt50);
        Tax tax51 = new Tax("Luxury Restaurant Tax", 12.0, "Indirect", "Restaurant Regulatory Authority",govt51);
        Tax tax52 = new Tax("Luxury Fashion Tax", 20.0, "Indirect", "Fashion Regulatory Authority",govt52);
        Tax tax53 = new Tax("Luxury Jewelry Tax", 25.0, "Indirect", "Jewelry Regulatory Authority",govt53);
        Tax tax54 = new Tax("Luxury Electronics Tax", 18.0, "Indirect", "Electronics Regulatory Authority",govt54);
        Tax tax55 = new Tax("Luxury Furniture Tax", 15.0, "Indirect", "Furniture Regulatory Authority",govt55);
        Tax tax56 = new Tax("Luxury Sports Tax", 20.0, "Indirect", "Sports Regulatory Authority",govt56);
        Tax tax57 = new Tax("Luxury Art Tax", 30.0, "Indirect", "Art Regulatory Authority",govt57);
        Tax tax58 = new Tax("Luxury Collectibles Tax", 25.0, "Indirect", "Collectibles Regulatory Authority",govt58);
        Tax tax59 = new Tax("Luxury Home Appliances Tax", 15.0, "Indirect", "Home Appliances Regulatory Authority",govt59);
        Tax tax60 = new Tax("Luxury Personal Care Tax", 10.0, "Indirect", "Personal Care Regulatory Authority",govt60);
        Tax tax61 = new Tax("Luxury Health Care Tax", 12.0, "Indirect", "Health Care Regulatory Authority",govt61);
        Tax tax62 = new Tax("Luxury Fitness Tax", 8.0, "Indirect", "Fitness Regulatory Authority",govt62);
        Tax tax63 = new Tax("Luxury Education Tax", 5.0, "Indirect", "Education Regulatory Authority",govt63);
        Tax tax64 = new Tax("Luxury Entertainment Tax", 10.0, "Indirect", "Entertainment Regulatory Authority",govt64);
        Tax tax65 = new Tax("Luxury Gaming Tax", 15.0, "Indirect", "Gaming Regulatory Authority",govt65);

        VariablePay vp1 = new VariablePay("Variable Pay 1", 5000.0, "Monthly", "Performance-based bonus", tax1);
        VariablePay vp2 = new VariablePay("Variable Pay 2", 7000.0, "Quarterly", "Sales commission", tax2);
        VariablePay vp3 = new VariablePay("Variable Pay 3", 3000.0, "Annually", "Project completion bonus", tax3);
        VariablePay vp4 = new VariablePay("Variable Pay 4", 4000.0, "Monthly", "Customer satisfaction bonus", tax4);
        VariablePay vp5 = new VariablePay("Variable Pay 5", 6000.0, "Quarterly", "Innovation bonus", tax5);
        VariablePay vp6 = new VariablePay("Variable Pay 6", 8000.0, "Annually", "Team performance bonus", tax6);
        VariablePay vp7 = new VariablePay("Variable Pay 7", 2000.0, "Monthly", "Attendance bonus", tax7);
        VariablePay vp8 = new VariablePay("Variable Pay 8", 3500.0, "Quarterly", "Training completion bonus", tax8);
        VariablePay vp9 = new VariablePay("Variable Pay 9", 4500.0, "Annually", "Leadership bonus", tax9);
        VariablePay vp10 = new VariablePay("Variable Pay 10", 5500.0, "Monthly", "Customer retention bonus", tax10);
        VariablePay vp11 = new VariablePay("Variable Pay 11", 6500.0, "Quarterly", "Market expansion bonus", tax11);
        VariablePay vp12= new VariablePay("Variable Pay 12", 7500.0, "Annually", "Cost-saving bonus", tax12);
        VariablePay vp13 = new VariablePay("Variable Pay 13", 8500.0, "Monthly", "Quality assurance bonus", tax13);
        VariablePay vp14 = new VariablePay("Variable Pay 14", 9500.0, "Quarterly", "Risk management bonus", tax14);
        VariablePay vp15 = new VariablePay("Variable Pay 15", 10500.0, "Annually", "Compliance bonus", tax15);
        VariablePay vp16 = new VariablePay("Variable Pay 16", 11500.0, "Monthly", "Sustainability bonus", tax16);
        VariablePay vp17 = new VariablePay("Variable Pay 17", 12500.0, "Quarterly", "Diversity and inclusion bonus", tax17);
        VariablePay vp18 = new VariablePay("Variable Pay 18", 13500.0, "Annually", "Community engagement bonus", tax18);
        VariablePay vp19 = new VariablePay("Variable Pay 19", 14500.0, "Monthly", "Employee referral bonus", tax19);
        VariablePay vp20 = new VariablePay("Variable Pay 20", 15500.0, "Quarterly", "Mentorship bonus", tax20);
        VariablePay vp21 = new VariablePay("Variable Pay 21", 16500.0, "Annually", "Knowledge sharing bonus", tax21);
        VariablePay vp22 = new VariablePay("Variable Pay 22", 17500.0, "Monthly", "Customer feedback bonus", tax22);
        VariablePay vp23 = new VariablePay("Variable Pay 23", 18500.0, "Quarterly", "Employee engagement bonus", tax23);
        VariablePay vp24 = new VariablePay("Variable Pay 24", 19500.0, "Annually", "Process improvement bonus", tax24);
        VariablePay vp25 = new VariablePay("Variable Pay 25", 20500.0, "Monthly", "Sales target bonus", tax25);
        VariablePay vp26 = new VariablePay("Variable Pay 26", 21500.0, "Quarterly", "Customer acquisition bonus", tax26);
        VariablePay vp27 = new VariablePay("Variable Pay 27", 22500.0, "Annually", "Market research bonus", tax27);
        VariablePay vp28 = new VariablePay("Variable Pay 28", 23500.0, "Monthly", "Product development bonus", tax28);
        VariablePay vp29 = new VariablePay("Variable Pay 29", 24500.0, "Quarterly", "Brand awareness bonus", tax29);
        VariablePay vp30 = new VariablePay("Variable Pay 30", 25500.0, "Annually", "Customer loyalty bonus", tax30);
        VariablePay vp31 = new VariablePay("Variable Pay 31", 26500.0, "Monthly", "Sales growth bonus", tax31);
        VariablePay vp32 = new VariablePay("Variable Pay 32", 27500.0, "Quarterly", "Market share bonus", tax32);
        VariablePay vp33 = new VariablePay("Variable Pay 33", 28500.0, "Annually", "Customer satisfaction improvement bonus", tax33);
        VariablePay vp34 = new VariablePay("Variable Pay 34", 29500.0, "Monthly", "Innovation implementation bonus", tax34);
        VariablePay vp35 = new VariablePay("Variable Pay 35", 30500.0, "Quarterly", "Cost reduction bonus", tax35);
        VariablePay vp36 = new VariablePay("Variable Pay 36", 31500.0, "Annually", "Revenue growth bonus", tax36);
        VariablePay vp37 = new VariablePay("Variable Pay 37", 32500.0, "Monthly", "Customer service excellence bonus", tax37);
        VariablePay vp38 = new VariablePay("Variable Pay 38", 33500.0, "Quarterly", "Operational efficiency bonus", tax38);
        VariablePay vp39 = new VariablePay("Variable Pay 39", 34500.0, "Annually", "Strategic initiative bonus", tax39);
        VariablePay vp40 = new VariablePay("Variable Pay 40", 35500.0, "Monthly", "Employee development bonus", tax40);
        VariablePay vp41 = new VariablePay("Variable Pay 41", 36500.0, "Quarterly", "Customer relationship bonus", tax41);
        VariablePay vp42 = new VariablePay("Variable Pay 42", 37500.0, "Annually", "Sales performance bonus", tax42);
        VariablePay vp43 = new VariablePay("Variable Pay 43", 38500.0, "Monthly", "Market penetration bonus", tax43);
        VariablePay vp44 = new VariablePay("Variable Pay 44", 39500.0, "Quarterly", "Customer retention improvement bonus", tax44);
        VariablePay vp45 = new VariablePay("Variable Pay 45", 40500.0, "Annually", "Product quality bonus", tax45);
        VariablePay vp46 = new VariablePay("Variable Pay 46", 41500.0, "Monthly", "Customer feedback improvement bonus", tax46);
        VariablePay vp47 = new VariablePay("Variable Pay 47", 42500.0, "Quarterly", "Sales strategy bonus", tax47);
        VariablePay vp48 = new VariablePay("Variable Pay 48", 43500.0, "Annually", "Customer engagement bonus", tax48);
        VariablePay vp49 = new VariablePay("Variable Pay 49", 44500.0, "Monthly", "Market analysis bonus", tax49);
        VariablePay vp50 = new VariablePay("Variable Pay 50", 45500.0, "Quarterly", "Sales training bonus", tax50);
        VariablePay vp51 = new VariablePay("Variable Pay 51", 46500.0, "Annually", "Customer service training bonus", tax51);
        VariablePay vp52 = new VariablePay("Variable Pay 52", 47500.0, "Monthly", "Sales coaching bonus", tax52);
        VariablePay vp53 = new VariablePay("Variable Pay 53", 48500.0, "Quarterly", "Customer relationship management bonus", tax53);
        VariablePay vp54 = new VariablePay("Variable Pay 54", 49500.0, "Annually", "Sales performance improvement bonus", tax54);
        VariablePay vp55 = new VariablePay("Variable Pay 55", 50500.0, "Monthly", "Customer satisfaction training bonus", tax55);
        VariablePay vp56 = new VariablePay("Variable Pay 56", 51500.0, "Quarterly", "Sales process improvement bonus", tax56);
        VariablePay vp57 = new VariablePay("Variable Pay 57", 52500.0, "Annually", "Customer service excellence training bonus", tax57);
        VariablePay vp58 = new VariablePay("Variable Pay 58", 53500.0, "Monthly", "Sales strategy training bonus", tax58);
        VariablePay vp59 = new VariablePay("Variable Pay 59", 54500.0, "Quarterly", "Customer engagement training bonus", tax59);
        VariablePay vp60 = new VariablePay("Variable Pay 60", 55500.0, "Annually", "Market research training bonus", tax60);
        VariablePay vp61 = new VariablePay("Variable Pay 61", 56500.0, "Monthly", "Sales performance coaching bonus", tax61);
        VariablePay vp62 = new VariablePay("Variable Pay 62", 57500.0, "Quarterly", "Customer service coaching bonus", tax62);
        VariablePay vp63 = new VariablePay("Variable Pay 63", 58500.0, "Annually", "Sales training coaching bonus", tax63);
        VariablePay vp64 = new VariablePay("Variable Pay 64", 59500.0, "Monthly", "Customer relationship coaching bonus", tax64);
        VariablePay vp65 = new VariablePay("Variable Pay 65", 60500.0, "Quarterly", "Sales strategy coaching bonus", tax65);

        Bonus b1 = new Bonus("Bonus 1", 1000.0, "Monthly", "Performance-based bonus", vp1);
        Bonus b2 = new Bonus("Bonus 2", 1500.0, "Quarterly", "Sales commission", vp2);
        Bonus b3 = new Bonus("Bonus 3", 800.0, "Annually", "Project completion bonus", vp3);
        Bonus b4 = new Bonus("Bonus 4", 1200.0, "Monthly", "Customer satisfaction bonus", vp4);
        Bonus b5 = new Bonus("Bonus 5", 1800.0, "Quarterly", "Innovation bonus", vp5);
        Bonus b6 = new Bonus("Bonus 6", 2000.0, "Annually", "Team performance bonus", vp6);
        Bonus b7 = new Bonus("Bonus 7", 600.0, "Monthly", "Attendance bonus", vp7);
        Bonus b8 = new Bonus("Bonus 8", 900.0, "Quarterly", "Training completion bonus", vp8);
        Bonus b9 = new Bonus("Bonus 9", 1100.0, "Annually", "Leadership bonus", vp9);
        Bonus b10 = new Bonus("Bonus 10", 1300.0, "Monthly", "Customer retention bonus", vp10);
        Bonus b11 = new Bonus("Bonus 11", 1400.0, "Quarterly", "Market expansion bonus", vp11);
        Bonus b12 = new Bonus("Bonus 12", 1600.0, "Annually", "Cost-saving bonus", vp12);
        Bonus b13 = new Bonus("Bonus 13", 1700.0, "Monthly", "Quality assurance bonus", vp13);
        Bonus b14 = new Bonus("Bonus 14", 1900.0, "Quarterly", "Risk management bonus", vp14);
        Bonus b15 = new Bonus("Bonus 15", 2100.0, "Annually", "Compliance bonus", vp15);
        Bonus b16 = new Bonus("Bonus 16", 2200.0, "Monthly", "Sustainability bonus", vp16);
        Bonus b17 = new Bonus("Bonus 17", 2300.0, "Quarterly", "Diversity and inclusion bonus", vp17);
        Bonus b18 = new Bonus("Bonus 18", 2400.0, "Annually", "Community engagement bonus", vp18);
        Bonus b19 = new Bonus("Bonus 19", 2500.0, "Monthly", "Employee referral bonus", vp19);
        Bonus b20 = new Bonus("Bonus 20", 2600.0, "Quarterly", "Mentorship bonus", vp20);
        Bonus b21 = new Bonus("Bonus 21", 2700.0, "Annually", "Knowledge sharing bonus", vp21);
        Bonus b22 = new Bonus("Bonus 22", 2800.0, "Monthly", "Customer feedback bonus", vp22);
        Bonus b23 = new Bonus("Bonus 23", 2900.0, "Quarterly", "Employee engagement bonus", vp23);
        Bonus b24 = new Bonus("Bonus 24", 3000.0, "Annually", "Process improvement bonus", vp24);
        Bonus b25 = new Bonus("Bonus 25", 3100.0, "Monthly", "Sales target bonus", vp25);
        Bonus b26 = new Bonus("Bonus 26", 3200.0, "Quarterly", "Customer acquisition bonus", vp26);
        Bonus b27 = new Bonus("Bonus 27", 3300.0, "Annually", "Market research bonus", vp27);
        Bonus b28 = new Bonus("Bonus 28", 3400.0, "Monthly", "Product development bonus", vp28);
        Bonus b29 = new Bonus("Bonus 29", 3500.0, "Quarterly", "Brand awareness bonus", vp29);
        Bonus b30 = new Bonus("Bonus 30", 3600.0, "Annually", "Customer loyalty bonus", vp30);
        Bonus b31 = new Bonus("Bonus 31", 3700.0, "Monthly", "Sales growth bonus", vp31);
        Bonus b32 = new Bonus("Bonus 32", 3800.0, "Quarterly", "Market share bonus", vp32);
        Bonus b33 = new Bonus("Bonus 33", 3900.0, "Annually", "Customer satisfaction improvement bonus", vp33);
        Bonus b34 = new Bonus("Bonus 34", 4000.0, "Monthly", "Innovation implementation bonus", vp34);
        Bonus b35 = new Bonus("Bonus 35", 4100.0, "Quarterly", "Cost reduction bonus", vp35);
        Bonus b36 = new Bonus("Bonus 36", 4200.0, "Annually", "Revenue growth bonus", vp36);
        Bonus b37 = new Bonus("Bonus 37", 4300.0, "Monthly", "Customer service excellence bonus", vp37);
        Bonus b38 = new Bonus("Bonus 38", 4400.0, "Quarterly", "Operational efficiency bonus", vp38);
        Bonus b39 = new Bonus("Bonus 39", 4500.0, "Annually", "Strategic initiative bonus", vp39);
        Bonus b40 = new Bonus("Bonus 40", 4600.0, "Monthly", "Employee development bonus", vp40);
        Bonus b41 = new Bonus("Bonus 41", 4700.0, "Quarterly", "Customer relationship bonus", vp41);
        Bonus b42 = new Bonus("Bonus 42", 4800.0, "Annually", "Sales performance bonus", vp42);
        Bonus b43 = new Bonus("Bonus 43", 4900.0, "Monthly", "Market penetration bonus", vp43);
        Bonus b44 = new Bonus("Bonus 44", 5000.0, "Quarterly", "Customer retention improvement bonus", vp44);
        Bonus b45 = new Bonus("Bonus 45", 5100.0, "Annually", "Product quality bonus", vp45);
        Bonus b46 = new Bonus("Bonus 46", 5200.0, "Monthly", "Customer feedback improvement bonus", vp46);
        Bonus b47 = new Bonus("Bonus 47", 5300.0, "Quarterly", "Sales strategy bonus", vp47);
        Bonus b48 = new Bonus("Bonus 48", 5400.0, "Annually", "Customer engagement bonus", vp48);
        Bonus b49 = new Bonus("Bonus 49", 5500.0, "Monthly", "Market analysis bonus", vp49);
        Bonus b50 = new Bonus("Bonus 50", 5600.0, "Quarterly", "Sales training bonus", vp50);
        Bonus b51 = new Bonus("Bonus 51", 5700.0, "Annually", "Customer service training bonus", vp51);
        Bonus b52 = new Bonus("Bonus 52", 5800.0, "Monthly", "Sales coaching bonus", vp52);
        Bonus b53 = new Bonus("Bonus 53", 5900.0, "Quarterly", "Customer relationship management bonus", vp53);
        Bonus b54 = new Bonus("Bonus 54", 6000.0, "Annually", "Sales performance improvement bonus", vp54);
        Bonus b55 = new Bonus("Bonus 55", 6100.0, "Monthly", "Customer satisfaction training bonus", vp55);
        Bonus b56 = new Bonus("Bonus 56", 6200.0, "Quarterly", "Sales process improvement bonus", vp56);
        Bonus b57 = new Bonus("Bonus 57", 6300.0, "Annually", "Customer service excellence training bonus", vp57);
        Bonus b58 = new Bonus("Bonus 58", 6400.0, "Monthly", "Sales strategy training bonus", vp58);
        Bonus b59 = new Bonus("Bonus 59", 6500.0, "Quarterly", "Customer engagement training bonus", vp59);
        Bonus b60 = new Bonus("Bonus 60", 6600.0, "Annually", "Market research training bonus", vp60);
        Bonus b61 = new Bonus("Bonus 61", 6700.0, "Monthly", "Sales performance coaching bonus", vp61);
        Bonus b62 = new Bonus("Bonus 62", 6800.0, "Quarterly", "Customer service coaching bonus", vp62);
        Bonus b63 = new Bonus("Bonus 63", 6900.0, "Annually", "Sales training coaching bonus", vp63);
        Bonus b64 = new Bonus("Bonus 64", 7000.0, "Monthly", "Customer relationship coaching bonus", vp64);
        Bonus b65 = new Bonus("Bonus 65", 7100.0, "Quarterly", "Sales strategy coaching bonus", vp65);


        SalaryExpectation salaryExpectation1 = new SalaryExpectation("Software Developer", 850000.0, "INR", "Annual", b1);
        SalaryExpectation salaryExpectation2 = new SalaryExpectation("Data Scientist", 950000.0, "INR", "Annual", b2);
        SalaryExpectation salaryExpectation3 = new SalaryExpectation("Product Manager", 1200000.0, "INR", "Annual", b3);
        SalaryExpectation salaryExpectation4 = new SalaryExpectation("UI/UX Designer", 780000.0, "INR", "Annual", b4);
        SalaryExpectation salaryExpectation5 = new SalaryExpectation("Business Analyst", 730000.0, "INR", "Annual", b5);
        SalaryExpectation salaryExpectation6 = new SalaryExpectation("QA Engineer", 670000.0, "INR", "Annual", b6);
        SalaryExpectation salaryExpectation7 = new SalaryExpectation("DevOps Engineer", 910000.0, "INR", "Annual", b7);
        SalaryExpectation salaryExpectation8 = new SalaryExpectation("Frontend Developer", 800000.0, "INR", "Annual", b8);
        SalaryExpectation salaryExpectation9 = new SalaryExpectation("Backend Developer", 870000.0, "INR", "Annual", b9);
        SalaryExpectation salaryExpectation10 = new SalaryExpectation("Full Stack Developer", 950000.0, "INR", "Annual", b10);
        SalaryExpectation salaryExpectation11 = new SalaryExpectation("Cloud Architect", 1600000.0, "INR", "Annual", b11);
        SalaryExpectation salaryExpectation12 = new SalaryExpectation("Cybersecurity Analyst", 920000.0, "INR", "Annual", b12);
        SalaryExpectation salaryExpectation13 = new SalaryExpectation("ML Engineer", 1100000.0, "INR", "Annual", b13);
        SalaryExpectation salaryExpectation14 = new SalaryExpectation("AI Engineer", 1300000.0, "INR", "Annual", b14);
        SalaryExpectation salaryExpectation15 = new SalaryExpectation("Technical Writer", 600000.0, "INR", "Annual", b15);
        SalaryExpectation salaryExpectation16 = new SalaryExpectation("Scrum Master", 970000.0, "INR", "Annual", b16);
        SalaryExpectation salaryExpectation17 = new SalaryExpectation("Project Manager", 1250000.0, "INR", "Annual", b17);
        SalaryExpectation salaryExpectation18 = new SalaryExpectation("Solution Architect", 1400000.0, "INR", "Annual", b18);
        SalaryExpectation salaryExpectation19 = new SalaryExpectation("Database Administrator", 810000.0, "INR", "Annual", b19);
        SalaryExpectation salaryExpectation20 = new SalaryExpectation("System Administrator", 730000.0, "INR", "Annual", b20);
        SalaryExpectation salaryExpectation21 = new SalaryExpectation("Blockchain Developer", 1350000.0, "INR", "Annual", b21);
        SalaryExpectation salaryExpectation22 = new SalaryExpectation("Penetration Tester", 990000.0, "INR", "Annual", b22);
        SalaryExpectation salaryExpectation23 = new SalaryExpectation("IT Support Specialist", 560000.0, "INR", "Annual", b23);
        SalaryExpectation salaryExpectation24 = new SalaryExpectation("Network Engineer", 760000.0, "INR", "Annual", b24);
        SalaryExpectation salaryExpectation25 = new SalaryExpectation("Data Engineer", 1050000.0, "INR", "Annual", b25);
        SalaryExpectation salaryExpectation26 = new SalaryExpectation("Research Scientist", 1450000.0, "INR", "Annual", b26);
        SalaryExpectation salaryExpectation27 = new SalaryExpectation("Embedded Systems Engineer", 890000.0, "INR", "Annual", b27);
        SalaryExpectation salaryExpectation28 = new SalaryExpectation("Mobile App Developer", 850000.0, "INR", "Annual", b28);
        SalaryExpectation salaryExpectation29 = new SalaryExpectation("Game Developer", 920000.0, "INR", "Annual", b29);
        SalaryExpectation salaryExpectation30 = new SalaryExpectation("Hardware Engineer", 880000.0, "INR", "Annual", b30);
        SalaryExpectation salaryExpectation31 = new SalaryExpectation("Digital Marketer", 610000.0, "INR", "Annual", b31);
        SalaryExpectation salaryExpectation32 = new SalaryExpectation("SEO Specialist", 570000.0, "INR", "Annual", b32);
        SalaryExpectation salaryExpectation33 = new SalaryExpectation("Content Strategist", 650000.0, "INR", "Annual", b33);
        SalaryExpectation salaryExpectation34 = new SalaryExpectation("Graphic Designer", 540000.0, "INR", "Annual", b34);
        SalaryExpectation salaryExpectation35 = new SalaryExpectation("Tech Lead", 1450000.0, "INR", "Annual", b35);
        SalaryExpectation salaryExpectation36 = new SalaryExpectation("Engineering Manager", 1700000.0, "INR", "Annual", b36);
        SalaryExpectation salaryExpectation37 = new SalaryExpectation("Cloud Consultant", 1550000.0, "INR", "Annual", b37);
        SalaryExpectation salaryExpectation38 = new SalaryExpectation("Site Reliability Engineer", 1250000.0, "INR", "Annual", b38);
        SalaryExpectation salaryExpectation39 = new SalaryExpectation("Platform Engineer", 1120000.0, "INR", "Annual", b39);
        SalaryExpectation salaryExpectation40 = new SalaryExpectation("Analytics Consultant", 980000.0, "INR", "Annual", b40);
        SalaryExpectation salaryExpectation41 = new SalaryExpectation("BI Developer", 860000.0, "INR", "Annual", b41);
        SalaryExpectation salaryExpectation42 = new SalaryExpectation("ETL Developer", 870000.0, "INR", "Annual", b42);
        SalaryExpectation salaryExpectation43 = new SalaryExpectation("CRM Specialist", 750000.0, "INR", "Annual", b43);
        SalaryExpectation salaryExpectation44 = new SalaryExpectation("SAP Consultant", 1400000.0, "INR", "Annual", b44);
        SalaryExpectation salaryExpectation45 = new SalaryExpectation("Salesforce Developer", 1300000.0, "INR", "Annual", b45);
        SalaryExpectation salaryExpectation46 = new SalaryExpectation("Technical Support Engineer", 600000.0, "INR", "Annual", b46);
        SalaryExpectation salaryExpectation47 = new SalaryExpectation("Application Support Analyst", 720000.0, "INR", "Annual", b47);
        SalaryExpectation salaryExpectation48 = new SalaryExpectation("Test Automation Engineer", 810000.0, "INR", "Annual", b48);
        SalaryExpectation salaryExpectation49 = new SalaryExpectation("Game Tester", 500000.0, "INR", "Annual", b49);
        SalaryExpectation salaryExpectation50 = new SalaryExpectation("AR/VR Developer", 1250000.0, "INR", "Annual", b50);
        SalaryExpectation salaryExpectation51 = new SalaryExpectation("Robotics Engineer", 1450000.0, "INR", "Annual", b51);
        SalaryExpectation salaryExpectation52 = new SalaryExpectation("NLP Engineer", 1320000.0, "INR", "Annual", b52);
        SalaryExpectation salaryExpectation53 = new SalaryExpectation("Computer Vision Engineer", 1380000.0, "INR", "Annual", b53);
        SalaryExpectation salaryExpectation54 = new SalaryExpectation("Simulation Engineer", 1100000.0, "INR", "Annual", b54);
        SalaryExpectation salaryExpectation55 = new SalaryExpectation("Bioinformatics Scientist", 1250000.0, "INR", "Annual", b55);
        SalaryExpectation salaryExpectation56 = new SalaryExpectation("Quantum Computing Researcher", 2000000.0, "INR", "Annual", b56);
        SalaryExpectation salaryExpectation57 = new SalaryExpectation("Ethical Hacker", 1200000.0, "INR", "Annual", b57);
        SalaryExpectation salaryExpectation58 = new SalaryExpectation("Game AI Developer", 1350000.0, "INR", "Annual", b58);
        SalaryExpectation salaryExpectation59 = new SalaryExpectation("Firmware Engineer", 890000.0, "INR", "Annual", b59);
        SalaryExpectation salaryExpectation60 = new SalaryExpectation("Multimedia Programmer", 720000.0, "INR", "Annual", b60);
        SalaryExpectation salaryExpectation61 = new SalaryExpectation("E-Commerce Analyst", 830000.0, "INR", "Annual", b61);
        SalaryExpectation salaryExpectation62 = new SalaryExpectation("Financial Systems Analyst", 930000.0, "INR", "Annual", b62);
        SalaryExpectation salaryExpectation63 = new SalaryExpectation("Data Privacy Officer", 1450000.0, "INR", "Annual", b63);
        SalaryExpectation salaryExpectation64 = new SalaryExpectation("IoT Specialist", 1280000.0, "INR", "Annual", b64);
        SalaryExpectation salaryExpectation65 = new SalaryExpectation("AI Researcher", 1800000.0, "INR", "Annual", b65);

        Criteria criteria1 = new Criteria("Software Developer", "Java, Spring Boot", 2, "Bangalore", salaryExpectation1);
        Criteria criteria2 = new Criteria("Data Scientist", "Python, ML, Statistics", 3, "Hyderabad", salaryExpectation2);
        Criteria criteria3 = new Criteria("Product Manager", "Agile, Scrum, UX", 5, "Mumbai", salaryExpectation3);
        Criteria criteria4 = new Criteria("UI/UX Designer", "Figma, Adobe XD", 2, "Delhi", salaryExpectation4);
        Criteria criteria5 = new Criteria("Business Analyst", "SQL, Tableau", 2, "Pune", salaryExpectation5);
        Criteria criteria6 = new Criteria("DevOps Engineer", "Docker, Kubernetes", 3, "Chennai", salaryExpectation6);
        Criteria criteria7 = new Criteria("Backend Developer", "Node.js, MongoDB", 2, "Noida", salaryExpectation7);
        Criteria criteria8 = new Criteria("Frontend Developer", "React, JavaScript", 2, "Bangalore", salaryExpectation8);
        Criteria criteria9 = new Criteria("Cybersecurity Analyst", "Networking, SIEM", 4, "Mumbai", salaryExpectation9);
        Criteria criteria10 = new Criteria("Cloud Engineer", "AWS, Terraform", 3, "Hyderabad", salaryExpectation10);
        Criteria criteria11 = new Criteria("Full Stack Developer", "MERN Stack", 2, "Delhi", salaryExpectation11);
        Criteria criteria12 = new Criteria("AI Engineer", "TensorFlow, Deep Learning", 3, "Pune", salaryExpectation12);
        Criteria criteria13 = new Criteria("Mobile Developer", "Kotlin, Flutter", 2, "Bangalore", salaryExpectation13);
        Criteria criteria14 = new Criteria("System Analyst", "SDLC, UML", 5, "Chennai", salaryExpectation14);
        Criteria criteria15 = new Criteria("Network Engineer", "Cisco, Routing", 3, "Hyderabad", salaryExpectation15);
        Criteria criteria16 = new Criteria("Technical Writer", "Markdown, Docs", 2, "Remote", salaryExpectation16);
        Criteria criteria17 = new Criteria("QA Engineer", "Selenium, JUnit", 2, "Bangalore", salaryExpectation17);
        Criteria criteria18 = new Criteria("Blockchain Developer", "Solidity, Web3", 1, "Pune", salaryExpectation18);
        Criteria criteria19 = new Criteria("VR Developer", "Unity, C#", 1, "Mumbai", salaryExpectation19);
        Criteria criteria20 = new Criteria("Game Developer", "C++, Unreal", 3, "Chennai", salaryExpectation20);
        Criteria criteria21 = new Criteria("AI Researcher", "NLP, GANs", 4, "Delhi", salaryExpectation21);
        Criteria criteria22 = new Criteria("Big Data Engineer", "Hadoop, Spark", 4, "Bangalore", salaryExpectation22);
        Criteria criteria23 = new Criteria("Data Engineer", "ETL, Python", 2, "Hyderabad", salaryExpectation23);
        Criteria criteria24 = new Criteria("Security Engineer", "Ethical Hacking, Linux", 3, "Mumbai", salaryExpectation24);
        Criteria criteria25 = new Criteria("Database Admin", "SQL Server, Oracle", 5, "Noida", salaryExpectation25);
        Criteria criteria26 = new Criteria("ML Ops Engineer", "MLFlow, Kubernetes", 3, "Bangalore", salaryExpectation26);
        Criteria criteria27 = new Criteria("Game Designer", "Game Logic, Sketch", 2, "Pune", salaryExpectation27);
        Criteria criteria28 = new Criteria("Graphic Designer", "Photoshop, Illustrator", 2, "Delhi", salaryExpectation28);
        Criteria criteria29 = new Criteria("Technical Support", "Troubleshooting, CRM", 1, "Remote", salaryExpectation29);
        Criteria criteria30 = new Criteria("IT Consultant", "Tech Strategy, ITIL", 6, "Chennai", salaryExpectation30);
        Criteria criteria31 = new Criteria("Penetration Tester", "Metasploit, Kali", 3, "Bangalore", salaryExpectation31);
        Criteria criteria32 = new Criteria("Chatbot Developer", "Rasa, NLP", 2, "Hyderabad", salaryExpectation32);
        Criteria criteria33 = new Criteria("Hardware Engineer", "PCB, Embedded C", 2, "Noida", salaryExpectation33);
        Criteria criteria34 = new Criteria("Bioinformatics Engineer", "Genomics, Python", 4, "Mumbai", salaryExpectation34);
        Criteria criteria35 = new Criteria("Embedded Systems Dev", "RTOS, C", 3, "Chennai", salaryExpectation35);
        Criteria criteria36 = new Criteria("Digital Marketer", "SEO, Analytics", 2, "Delhi", salaryExpectation36);
        Criteria criteria37 = new Criteria("Recruiter", "ATS, Interviewing", 1, "Remote", salaryExpectation37);
        Criteria criteria38 = new Criteria("Cloud Security Engineer", "IAM, VPC", 4, "Bangalore", salaryExpectation38);
        Criteria criteria39 = new Criteria("Logistics Analyst", "SCM, ERP", 2, "Pune", salaryExpectation39);
        Criteria criteria40 = new Criteria("IT Auditor", "ISO, Risk Mgmt", 5, "Mumbai", salaryExpectation40);
        Criteria criteria41 = new Criteria("ETL Developer", "Informatica, SQL", 2, "Hyderabad", salaryExpectation41);
        Criteria criteria42 = new Criteria("Scrum Master", "Agile, Jira", 4, "Bangalore", salaryExpectation42);
        Criteria criteria43 = new Criteria("SAP Consultant", "SAP HANA, ABAP", 5, "Chennai", salaryExpectation43);
        Criteria criteria44 = new Criteria("ERP Specialist", "Oracle ERP, BI", 3, "Noida", salaryExpectation44);
        Criteria criteria45 = new Criteria("Automation Engineer", "Python, Jenkins", 2, "Delhi", salaryExpectation45);
        Criteria criteria46 = new Criteria("Tech Architect", "Design Patterns, Microservices", 7, "Bangalore", salaryExpectation46);
        Criteria criteria47 = new Criteria("Content Strategist", "Blogs, SEO", 1, "Remote", salaryExpectation47);
        Criteria criteria48 = new Criteria("Data Visualizer", "Power BI, Tableau", 2, "Mumbai", salaryExpectation48);
        Criteria criteria49 = new Criteria("Research Analyst", "Qualitative Analysis", 2, "Pune", salaryExpectation49);
        Criteria criteria50 = new Criteria("Operations Manager", "Team Handling, ERP", 5, "Hyderabad", salaryExpectation50);
        Criteria criteria51 = new Criteria("Legal Tech Associate", "Contracts, AI tools", 3, "Delhi", salaryExpectation51);
        Criteria criteria52 = new Criteria("3D Modeler", "Blender, Maya", 2, "Chennai", salaryExpectation52);
        Criteria criteria53 = new Criteria("Creative Director", "Ad Concepts, Campaigns", 6, "Mumbai", salaryExpectation53);
        Criteria criteria54 = new Criteria("Robotics Engineer", "ROS, Python", 4, "Bangalore", salaryExpectation54);
        Criteria criteria55 = new Criteria("Game Tester", "Debugging, QA", 1, "Pune", salaryExpectation55);
        Criteria criteria56 = new Criteria("Motion Designer", "After Effects", 2, "Hyderabad", salaryExpectation56);
        Criteria criteria57 = new Criteria("SEO Analyst", "Google Analytics", 1, "Delhi", salaryExpectation57);
        Criteria criteria58 = new Criteria("HR Manager", "Payroll, Compliance", 4, "Mumbai", salaryExpectation58);
        Criteria criteria59 = new Criteria("VR Tester", "Bug Reporting, QA", 2, "Bangalore", salaryExpectation59);
        Criteria criteria60 = new Criteria("Digital Twin Dev", "Simulation, IoT", 3, "Chennai", salaryExpectation60);
        Criteria criteria61 = new Criteria("Ethical Hacker", "CEH, NMAP", 3, "Noida", salaryExpectation61);
        Criteria criteria62 = new Criteria("ML Scientist", "XGBoost, Research", 5, "Hyderabad", salaryExpectation62);
        Criteria criteria63 = new Criteria("Platform Engineer", "K8s, CI/CD", 3, "Bangalore", salaryExpectation63);
        Criteria criteria64 = new Criteria("Smart Contract Dev", "Solidity, DeFi", 2, "Remote", salaryExpectation64);
        Criteria criteria65 = new Criteria("Innovation Lead", "R&D, Patents", 6, "Mumbai", salaryExpectation65);

        List<Criteria> criteriaList1 = new ArrayList<>();
        criteriaList1.add(criteria1);
        criteriaList1.add(criteria2);
        Role role1 = new Role("Software Developer", "Develop and maintain software applications","IT","Java",criteriaList1);
        List<Criteria> criteriaList2 = new ArrayList<>();
        criteriaList2.add(criteria3);
        criteriaList2.add(criteria4);
        Role role2 = new Role("Data Scientist", "Analyze and interpret complex data sets","IT","Python",criteriaList2);
        List<Criteria> criteriaList3 = new ArrayList<>();
        criteriaList3.add(criteria5);
        criteriaList3.add(criteria6);
        Role role3 = new Role("Product Manager", "Oversee product development and strategy","IT","Agile",criteriaList3);
        List<Criteria> criteriaList4 = new ArrayList<>();
        criteriaList4.add(criteria7);
        criteriaList4.add(criteria8);
        Role role4 = new Role("UI/UX Designer", "Design user interfaces and experiences","IT","Figma",criteriaList4);
        List<Criteria> criteriaList5 = new ArrayList<>();
        criteriaList5.add(criteria9);
        criteriaList5.add(criteria10);
        Role role5 = new Role("Business Analyst", "Analyze business processes and requirements","IT","SQL",criteriaList5);
        List<Criteria> criteriaList6 = new ArrayList<>();
        criteriaList6.add(criteria11);
        criteriaList6.add(criteria12);
        Role role6 = new Role("QA Engineer", "Ensure software quality through testing","IT","Selenium",criteriaList6);
        List<Criteria> criteriaList7 = new ArrayList<>();
        criteriaList7.add(criteria13);
        criteriaList7.add(criteria14);
        Role role7 = new Role("DevOps Engineer", "Automate and streamline development processes","IT","Docker",criteriaList7);
        List<Criteria> criteriaList8 = new ArrayList<>();
        criteriaList8.add(criteria15);
        criteriaList8.add(criteria16);
        Role role8 = new Role("Frontend Developer", "Develop client-side applications","IT","React",criteriaList8);
        List<Criteria> criteriaList9 = new ArrayList<>();
        criteriaList9.add(criteria17);
        criteriaList9.add(criteria18);
        Role role9 = new Role("Backend Developer", "Develop server-side applications","IT","Node.js",criteriaList9);
        List<Criteria> criteriaList10 = new ArrayList<>();
        criteriaList10.add(criteria19);
        criteriaList10.add(criteria20);
        Role role10 = new Role("Full Stack Developer", "Develop both client-side and server-side applications","IT","MERN Stack",criteriaList10);
        List<Criteria> criteriaList11 = new ArrayList<>();
        criteriaList11.add(criteria21);
        criteriaList11.add(criteria22);
        Role role11 = new Role("Cloud Architect", "Design and manage cloud infrastructure","IT","AWS",criteriaList11);
        List<Criteria> criteriaList12 = new ArrayList<>();
        criteriaList12.add(criteria23);
        criteriaList12.add(criteria24);
        Role role12 = new Role("Cybersecurity Analyst", "Protect systems and networks from cyber threats","IT","Networking",criteriaList12);
        List<Criteria> criteriaList13 = new ArrayList<>();
        criteriaList13.add(criteria25);
        criteriaList13.add(criteria26);
        Role role13 = new Role("ML Engineer", "Develop machine learning models and algorithms","IT","TensorFlow",criteriaList13);
        List<Criteria> criteriaList14 = new ArrayList<>();
        criteriaList14.add(criteria27);
        criteriaList14.add(criteria28);
        Role role14 = new Role("AI Engineer", "Develop AI applications and systems","IT","NLP",criteriaList14);
        List<Criteria> criteriaList15 = new ArrayList<>();
        criteriaList15.add(criteria29);
        criteriaList15.add(criteria30);
        Role role15 = new Role("Technical Writer", "Create technical documentation and manuals","IT","Markdown",criteriaList15);
        List<Criteria> criteriaList16 = new ArrayList<>();
        criteriaList16.add(criteria31);
        criteriaList16.add(criteria32);
        Role role16 = new Role("Scrum Master", "Facilitate Agile development processes","IT","Agile",criteriaList16);
        List<Criteria> criteriaList17 = new ArrayList<>();
        criteriaList17.add(criteria33);
        criteriaList17.add(criteria34);
        Role role17 = new Role("Project Manager", "Plan and execute projects","IT","SDLC",criteriaList17);
        List<Criteria> criteriaList18 = new ArrayList<>();
        criteriaList18.add(criteria35);
        criteriaList18.add(criteria36);
        Role role18 = new Role("Solution Architect", "Design software solutions and architectures","IT","Design Patterns",criteriaList18);
        List<Criteria> criteriaList19 = new ArrayList<>();
        criteriaList19.add(criteria37);
        criteriaList19.add(criteria38);
        Role role19 = new Role("Database Administrator", "Manage and maintain databases","IT","SQL Server",criteriaList19);
        List<Criteria> criteriaList20 = new ArrayList<>();
        criteriaList20.add(criteria39);
        criteriaList20.add(criteria40);
        Role role20 = new Role("System Administrator", "Manage and maintain IT systems","IT","Linux",criteriaList20);
        List<Criteria> criteriaList21 = new ArrayList<>();
        criteriaList21.add(criteria41);
        criteriaList21.add(criteria42);
        Role role21 = new Role("Blockchain Developer", "Develop blockchain applications and smart contracts","IT","Solidity",criteriaList21);
        List<Criteria> criteriaList22 = new ArrayList<>();
        criteriaList22.add(criteria43);
        criteriaList22.add(criteria44);
        Role role22 = new Role("Penetration Tester", "Test systems for vulnerabilities","IT","Kali Linux",criteriaList22);
        List<Criteria> criteriaList23 = new ArrayList<>();
        criteriaList23.add(criteria45);
        criteriaList23.add(criteria46);
        Role role23 = new Role("IT Support Specialist", "Provide technical support to users","IT","Troubleshooting",criteriaList23);
        List<Criteria> criteriaList24 = new ArrayList<>();
        criteriaList24.add(criteria47);
        criteriaList24.add(criteria48);
        Role role24 = new Role("Network Engineer", "Design and maintain network infrastructure","IT","Cisco",criteriaList24);
        List<Criteria> criteriaList25 = new ArrayList<>();
        criteriaList25.add(criteria49);
        criteriaList25.add(criteria50);
        Role role25 = new Role("Data Engineer", "Build and maintain data pipelines","IT","ETL",criteriaList25);
        List<Criteria> criteriaList26 = new ArrayList<>();
        criteriaList26.add(criteria51);
        criteriaList26.add(criteria52);
        Role role26 = new Role("Research Scientist", "Conduct research and development","IT","Genomics",criteriaList26);
        List<Criteria> criteriaList27 = new ArrayList<>();
        criteriaList27.add(criteria53);
        criteriaList27.add(criteria54);
        Role role27 = new Role("Embedded Systems Engineer", "Design and develop embedded systems","IT","RTOS",criteriaList27);
        List<Criteria> criteriaList28 = new ArrayList<>();
        criteriaList28.add(criteria55);
        criteriaList28.add(criteria56);
        Role role28 = new Role("Mobile App Developer", "Develop mobile applications","IT","Kotlin",criteriaList28);
        List<Criteria> criteriaList29 = new ArrayList<>();
        criteriaList29.add(criteria57);
        criteriaList29.add(criteria58);
        Role role29 = new Role("Game Developer", "Develop video games and interactive applications","IT","C++",criteriaList29);
        List<Criteria> criteriaList30 = new ArrayList<>();
        criteriaList30.add(criteria59);
        criteriaList30.add(criteria60);
        Role role30 = new Role("Hardware Engineer", "Design and develop hardware components","IT","PCB Design",criteriaList30);
        List<Criteria> criteriaList31 = new ArrayList<>();
        criteriaList31.add(criteria61);
        criteriaList31.add(criteria62);
        Role role31 = new Role("Digital Marketer", "Plan and execute digital marketing campaigns","Marketing","SEO",criteriaList31);
        List<Criteria> criteriaList32 = new ArrayList<>();
        criteriaList32.add(criteria63);
        criteriaList32.add(criteria64);
        Role role32 = new Role("SEO Specialist", "Optimize websites for search engines","Marketing","Google Analytics",criteriaList32);
        List<Criteria> criteriaList33 = new ArrayList<>();
        criteriaList33.add(criteria65);
        Role role33 = new Role("Content Strategist", "Develop content strategies and plans","Marketing","Content Marketing",criteriaList33);
        List<Criteria> criteriaList34 = new ArrayList<>();
        criteriaList34.add(criteria1);
        criteriaList34.add(criteria2);
        Role role34 = new Role("Graphic Designer", "Create visual content for various platforms","Marketing","Adobe Creative Suite",criteriaList34);
        List<Criteria> criteriaList35 = new ArrayList<>();
        criteriaList35.add(criteria3);
        criteriaList35.add(criteria4);
        Role role35 = new Role("Tech Lead", "Lead technical teams and projects","IT","Leadership",criteriaList35);
        List<Criteria> criteriaList36 = new ArrayList<>();
        criteriaList36.add(criteria5);
        criteriaList36.add(criteria6);
        Role role36 = new Role("Engineering Manager", "Manage engineering teams and projects","IT","Team Management",criteriaList36);
        List<Criteria> criteriaList37 = new ArrayList<>();
        criteriaList37.add(criteria7);
        criteriaList37.add(criteria8);
        Role role37 = new Role("Cloud Consultant", "Provide cloud solutions and strategies","IT","Cloud Computing",criteriaList37);
        List<Criteria> criteriaList38 = new ArrayList<>();
        criteriaList38.add(criteria9);
        criteriaList38.add(criteria10);
        Role role38 = new Role("Site Reliability Engineer", "Ensure reliability and performance of systems","IT","SRE",criteriaList38);
        List<Criteria> criteriaList39 = new ArrayList<>();
        criteriaList39.add(criteria11);
        criteriaList39.add(criteria12);
        Role role39 = new Role("Platform Engineer", "Build and maintain platform services","IT","Kubernetes",criteriaList39);
        List<Criteria> criteriaList40 = new ArrayList<>();
        criteriaList40.add(criteria13);
        criteriaList40.add(criteria14);
        Role role40 = new Role("Analytics Consultant", "Provide analytics solutions and insights","IT","Data Analysis",criteriaList40);
        List<Criteria> criteriaList41 = new ArrayList<>();
        criteriaList41.add(criteria15);
        criteriaList41.add(criteria16);
        Role role41 = new Role("BI Developer", "Develop business intelligence solutions","IT","Power BI",criteriaList41);
        List<Criteria> criteriaList42 = new ArrayList<>();
        criteriaList42.add(criteria17);
        criteriaList42.add(criteria18);
        Role role42 = new Role("ETL Developer", "Extract, transform, and load data","IT","Informatica",criteriaList42);
        List<Criteria> criteriaList43 = new ArrayList<>();
        criteriaList43.add(criteria19);
        criteriaList43.add(criteria20);
        Role role43 = new Role("CRM Specialist", "Manage customer relationship management systems","IT","Salesforce",criteriaList43);
        List<Criteria> criteriaList44 = new ArrayList<>();
        criteriaList44.add(criteria21);
        criteriaList44.add(criteria22);
        Role role44 = new Role("SAP Consultant", "Implement and support SAP solutions","IT","SAP HANA",criteriaList44);
        List<Criteria> criteriaList45 = new ArrayList<>();
        criteriaList45.add(criteria23);
        criteriaList45.add(criteria24);
        Role role45 = new Role("Salesforce Developer", "Develop and customize Salesforce applications","IT","Apex",criteriaList45);
        List<Criteria> criteriaList46 = new ArrayList<>();
        criteriaList46.add(criteria25);
        criteriaList46.add(criteria26);
        Role role46 = new Role("Technical Support Engineer", "Provide technical support and troubleshooting","IT","Customer Support",criteriaList46);
        List<Criteria> criteriaList47 = new ArrayList<>();
        criteriaList47.add(criteria27);
        criteriaList47.add(criteria28);
        Role role47 = new Role("Application Support Analyst", "Support and maintain applications","IT","Application Support",criteriaList47);
        List<Criteria> criteriaList48 = new ArrayList<>();
        criteriaList48.add(criteria29);
        criteriaList48.add(criteria30);
        Role role48 = new Role("Test Automation Engineer", "Automate software testing processes","IT","Selenium",criteriaList48);
        List<Criteria> criteriaList49 = new ArrayList<>();
        criteriaList49.add(criteria31);
        criteriaList49.add(criteria32);
        Role role49 = new Role("Game Tester", "Test video games for quality assurance","IT","Game Testing",criteriaList49);
        List<Criteria> criteriaList50 = new ArrayList<>();
        criteriaList50.add(criteria33);
        criteriaList50.add(criteria34);
        Role role50 = new Role("AR/VR Developer", "Develop augmented and virtual reality applications","IT","Unity",criteriaList50);
        List<Criteria> criteriaList51 = new ArrayList<>();
        criteriaList51.add(criteria35);
        criteriaList51.add(criteria36);
        Role role51 = new Role("Robotics Engineer", "Design and develop robotic systems","IT","ROS",criteriaList51);
        List<Criteria> criteriaList52 = new ArrayList<>();
        criteriaList52.add(criteria37);
        criteriaList52.add(criteria38);
        Role role52 = new Role("NLP Engineer", "Develop natural language processing applications","IT","NLP",criteriaList52);
        List<Criteria> criteriaList53 = new ArrayList<>();
        criteriaList53.add(criteria39);
        criteriaList53.add(criteria40);
        Role role53 = new Role("Computer Vision Engineer", "Develop computer vision applications","IT","OpenCV",criteriaList53);
        List<Criteria> criteriaList54 = new ArrayList<>();
        criteriaList54.add(criteria41);
        criteriaList54.add(criteria42);
        Role role54 = new Role("Simulation Engineer", "Develop simulation models and systems","IT","MATLAB",criteriaList54);
        List<Criteria> criteriaList55 = new ArrayList<>();
        criteriaList55.add(criteria43);
        criteriaList55.add(criteria44);
        Role role55 = new Role("Bioinformatics Scientist", "Analyze biological data using computational methods","IT","Bioinformatics",criteriaList55);
        List<Criteria> criteriaList56 = new ArrayList<>();
        criteriaList56.add(criteria45);
        criteriaList56.add(criteria46);
        Role role56 = new Role("Quantum Computing Researcher", "Conduct research in quantum computing","IT","Quantum Algorithms",criteriaList56);
        List<Criteria> criteriaList57 = new ArrayList<>();
        criteriaList57.add(criteria47);
        criteriaList57.add(criteria48);
        Role role57 = new Role("Ethical Hacker", "Test systems for security vulnerabilities","IT","Penetration Testing",criteriaList57);
        List<Criteria> criteriaList58 = new ArrayList<>();
        criteriaList58.add(criteria49);
        criteriaList58.add(criteria50);
        Role role58 = new Role("Game AI Developer", "Develop AI for video games","IT","Game AI",criteriaList58);
        List<Criteria> criteriaList59 = new ArrayList<>();
        criteriaList59.add(criteria51);
        criteriaList59.add(criteria52);
        Role role59 = new Role("Firmware Engineer", "Develop firmware for hardware devices","IT","Embedded Systems",criteriaList59);
        List<Criteria> criteriaList60 = new ArrayList<>();
        criteriaList60.add(criteria53);
        criteriaList60.add(criteria54);
        Role role60 = new Role("Multimedia Programmer", "Develop multimedia applications","IT","C++",criteriaList60);
        List<Criteria> criteriaList61 = new ArrayList<>();
        criteriaList61.add(criteria55);
        criteriaList61.add(criteria56);
        Role role61 = new Role("E-Commerce Analyst", "Analyze e-commerce data and trends","IT","E-Commerce",criteriaList61);
        List<Criteria> criteriaList62 = new ArrayList<>();
        criteriaList62.add(criteria57);
        criteriaList62.add(criteria58);
        Role role62 = new Role("Financial Systems Analyst", "Analyze financial systems and processes","IT","Finance",criteriaList62);
        List<Criteria> criteriaList63 = new ArrayList<>();
        criteriaList63.add(criteria59);
        criteriaList63.add(criteria60);
        Role role63 = new Role("Data Privacy Officer", "Ensure compliance with data privacy regulations","IT","Data Privacy",criteriaList63);
        List<Criteria> criteriaList64 = new ArrayList<>();
        criteriaList64.add(criteria61);
        criteriaList64.add(criteria62);
        Role role64 = new Role("IoT Specialist", "Develop Internet of Things applications","IT","IoT",criteriaList64);
        List<Criteria> criteriaList65 = new ArrayList<>();
        criteriaList65.add(criteria63);
        criteriaList65.add(criteria64);
        Role role65 = new Role("AI Researcher", "Conduct research in artificial intelligence","IT","AI Research",criteriaList65);


        
    }
}
